fix deploy that is failing due to incompatible Ruby version
fastlane/docs pull request #1034
Opened 2021-03-10 02:48 UTC by rogerluan

signet was upgraded here https://github.com/fastlane/docs/pull/1033/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR218 and CI started failing to deploy. This simple constrain of gem version should do the trick for now until we decide to upgrade Ruby.

2021-03-10 13:53 UTC, janpio commented
Can you link to a failing CI deploy that is affected by this?

2021-03-10 14:26 UTC, rogerluan commented
@janpio certainly! Updated the PR description with 2 failure links

2021-03-10 16:51 UTC, ainame commented
We can also bump the docker image to the latest 0.3.0 using Ruby 2.6

https://github.com/fastlane/docs/blob/a64b28ebfc4f6311106d19d7fe1120b70904c844/.circleci/config.yml#L6

https://github.com/fastlane/docker/pull/4
https://hub.docker.com/r/fastlanetools/ci/tags?page=1&ordering=last_updated

2021-03-10 17:04 UTC, ainame requested changes
I think we should bump the docker image to the latest 0.3.0 using Ruby 2.6 instead of keeping old rubygems used in this doc repo. Don't need to worry about breaking things here 😄 

https://github.com/fastlane/docs/blob/a64b28ebfc4f6311106d19d7fe1120b70904c844/.circleci/config.yml#L6

https://github.com/fastlane/docker/pull/4
https://hub.docker.com/r/fastlanetools/ci/tags?page=1&ordering=last_updated

2021-03-11 13:34 UTC, rogerluan commented
@ainame 😮 interesting! I've updated it, let's see if CI complains 😊

2021-03-11 13:44 UTC, rogerluan commented
Test passes, let's hope that Deploy passes too 😇 @ainame you're up!

2021-03-11 14:44 UTC, ainame approved these changes
LGTM

We'll then need to fix pipenv issue in Netlify's checks😬

2021-03-11 14:57 UTC, merged