Update broken link in beta-deployment.md
fastlane/docs pull request #1104
Opened 2021-10-02 12:39 UTC by Ian-Phelon

Corrected the link to the intended directory.

2021-10-02 12:42 UTC, Ian-Phelon commented
@googlebot I signed it!

2021-10-02 18:01 UTC, revolter requested changes
Great catch 👍🏻

2021-10-02 18:01 UTC, revolter commented on docs/getting-started/android/beta-deployment.md
> +If you would like to distribute your beta builds to Google Play, please make sure you've done the steps from [Setting up _supply_](../setup/#setting-up-supply) before continuing.
Please change this to
```suggestion
If you would like to distribute your beta builds to Google Play, please make sure you've done the steps from [Setting up _supply_](/getting-started/android/setup/#setting-up-supply) before continuing.
```
so it's consistent with the rest of the codebase (we don't use relative URLs at all).

2021-10-03 23:10 UTC, Ian-Phelon reviewed
Thanks for the help

2021-10-04 02:36 UTC, rogerluan approved these changes
LGTM 👍 Test failures are unrelated to this PR, I'm fine with merging this in 👌

2021-10-04 02:36 UTC, rogerluan commented
Thank you for your contribution @Ian-Phelon ! 🎉

2021-10-04 02:38 UTC, rogerluan commented
Ah, actually I can't merge it in because of the failed tests, even though they're unrelated to this PR. 😥 
@Ian-Phelon could you try taking care of them? It's failing because the docs on the page you edited are outdated, referring to an _action_ that doesn't exist anymore (`crashlytics`), because Crashlytics itself (the one from Fabric) kinda doesn't exist anymore 😅 idk exactly if there's an equivalent for this action, or if those sections/mentions could be deleted 🤔 thoughts @revolter ?

2021-10-04 04:32 UTC, revolter commented
Oh, I forgot. This only needs a rebase. I fixed the tests in #1103.

2021-10-04 04:33 UTC, revolter approved these changes

2021-10-04 13:01 UTC, rogerluan commented
Ahh amazing @revolter thanks!! 🌟

2021-10-04 13:01 UTC, merged

2021-10-04 13:38 UTC, Ian-Phelon commented
Thanks @revolter and @rogerluan for helping me to accomplish my first PR.