Chore : Fix typo in multiple files
fastlane/docs pull request #1219
Opened 2023-10-20 01:42 UTC by thapasusheel

This PR fix the typo that has been seen in various files.

```pseudo
distrbution > distribution
practies > practise
managment > management
unque > unique
configuraiton > configuration
```

2023-10-20 17:03 UTC, rogerluan commented on docs/generated/actions/appstore.md
> +Starting on December 8, 2020, Apple announced that developers are required to provide app privacy details that will help users understand an app's privacy practise. _deliver_ does not allow for updat
This has to be modified in https://github.com/fastlane/fastlane instead as it's autogenerated code 🙏

2023-10-20 17:03 UTC, rogerluan commented on docs/generated/actions/appstore.md
> +Starting on December 8, 2020, Apple announced that developers are required to provide app privacy details that will help users understand an app's privacy practise. _deliver_ does not allow for updat
And I think the expected word is actually `practices` :)

2023-10-20 17:03 UTC, rogerluan commented on docs/generated/actions/deliver.md
> +Starting on December 8, 2020, Apple announced that developers are required to provide app privacy details that will help users understand an app's privacy practise. _deliver_ does not allow for updat
Same

2023-10-20 17:03 UTC, rogerluan commented on docs/generated/available-plugins.md
> +> Automated version management and generator of release notes.
Same for this and all files under `/generated/` and `/plugins/` directories

2023-10-20 17:04 UTC, rogerluan commented
Thanks for noticing these and taking the initiative to fix them @thapasusheel ! 🤗 

Out of the changes you made, all of them except 1 belong to the main fastlane repo, could you adjust this PR? I'll fix the typos in the main repo meanwhile :)

2023-10-20 17:16 UTC, rogerluan commented on docs/generated/available-plugins.md
> +> Fork for: Automated version management and generator of release notes.
These references are pulled from 3rd party repositories. One repo made this typo, and 4 other repos forked it so the typo spread 😂 

Ref.: https://docs.fastlane.tools/plugins/available-plugins/

We'll have to revert these as this file gets autogenerated on every deploy 😅

2023-10-20 17:17 UTC, rogerluan commented on docs/plugins/available-plugins.md
> +> Sauce Labs android & ios configuration
Same

2023-10-20 17:17 UTC, rogerluan commented on docs/generated/available-plugins.md
> +> Automatic generate app build number unique and human readable friendly, like yymmHHMM. both support iOS and Android.
Same

2023-10-20 17:19 UTC, rogerluan commented
I addressed all I could here: https://github.com/fastlane/fastlane/pull/21589

2023-10-21 01:59 UTC, thapasusheel commented
@rogerluan Can you review it again?

2023-10-21 02:05 UTC, rogerluan requested changes
@thapasusheel not sure if you pushed any changes? The PR looks the same to me 🤔 

To be clear, only the changes made to `codemagic.md` are to be kept, the others should be reverted as they're autogenerated 🙏 

Thanks in advance!

2023-10-21 02:20 UTC, thapasusheel commented
@rogerluan  I have updated as per you have said. Can you review it again?

2023-10-21 04:44 UTC, rogerluan requested changes

2023-10-21 04:44 UTC, rogerluan commented on docs/best-practices/xcodebuild-formatters.md
> +# Specifify a local install of xcbeautify
```suggestion
# Specify a local installation of xcbeautify
```

(Typo + I think installation is either more correct or simply sounds better)

2023-10-21 04:45 UTC, rogerluan approved these changes
💪 thanks for your contributions @thapasusheel !

2023-10-21 07:02 UTC, merged