add that you need to have done an ad-hoc apk upload before supply init
fastlane/docs pull request #787
Opened 2019-02-21 07:15 UTC by asterixorobelix

2019-02-21 09:37 UTC, janpio commented
Very good point.

I thought we already had mentioned that somewhere though... maybe only on the `supply` page itself and not on the setup?

2019-02-21 16:55 UTC, asterixorobelix commented
@janpio this is documentation, no need to be DRY. In my opinion reiteration is good in documentation. this point was missed by me when I was reading the docs

2019-02-21 17:12 UTC, janpio commented on docs/getting-started/android/setup.md
> +For _supply_ to be able to initialize, you need to have successfully uploaded an apk to you Google Play Console app at least once.
```suggestion
For _supply_ to be able to initialize, you need to have successfully uploaded an APK to your app in the Google Play Console at least once.
```

2019-02-21 17:12 UTC, janpio commented
That wasn't a criticism, I was just trying to get the full picture.  
If we have similar wording somewhere else, we should make sure it is consistent.

2021-03-07 02:37 UTC, rogerluan requested changes

2021-03-07 02:37 UTC, rogerluan commented on docs/getting-started/android/setup.md
> +For _supply_ to be able to initialize, you need to have successfully uploaded an apk to you Google Play Console app at least once.
```suggestion
For _supply_ to be able to initialize, you need to have successfully uploaded an APK to your app in the Google Play Console at least once.
```

2021-03-07 02:43 UTC, rogerluan commented
Closing in favor of https://github.com/fastlane/docs/pull/1030

2021-03-07 02:43 UTC, closed without merging