Grammatical correction and slight rephrasing for clarity.
fastlane/docs pull request #986
Opened 2020-10-02 12:47 UTC by brendanpettis

2020-10-02 13:01 UTC, lyndsey-ferguson approved these changes

2021-03-07 04:22 UTC, rogerluan requested changes

2021-03-07 04:22 UTC, rogerluan commented on docs/getting-started/ios/screenshots.md
> +To automatically add device frames around all screenshots in the current directory and its subdirectories, just run
```suggestion
To automatically add device frames around all screenshots in the current directory and its subdirectories, just run:
```

2021-03-07 04:23 UTC, rogerluan approved these changes
Thanks for these small yet meaningful changes 🤗 I love grammar fixes! 🙈

2021-03-07 04:26 UTC, merged