jenkins-lts as a recommended way of installing Jenkins
fastlane/docs pull request #991
Opened 2020-10-13 21:34 UTC by art-divin

changed from jenkins to jenkins-lts as a recommended way of installing Jenkins

2020-10-13 21:35 UTC, art-divin commented
@googlebot I signed it!

2020-10-13 21:37 UTC, lyndsey-ferguson approved these changes
https://www.jenkins.io/download/lts/macos/

2020-10-15 14:53 UTC, rogerluan reviewed
This is cool :) thanks for the docs @lyndsey-ferguson !

Thanks for your first contribution @art-divin ❤️

2021-03-07 04:34 UTC, rogerluan requested changes

2021-03-07 04:34 UTC, rogerluan commented on docs/best-practices/continuous-integration/jenkins.md
>  The recommended way to install [Jenkins](http://jenkins-ci.org/) is through [homebrew](http://brew.sh/):
```suggestion
The recommended way to [install Jenkins on macOS](https://www.jenkins.io/download/lts/macos/) is through [homebrew](http://brew.sh/):
```

2021-03-07 04:34 UTC, rogerluan approved these changes
Thanks again for this contribution!

2021-03-07 04:43 UTC, merged